/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tugas_2;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Miechel
 */
public class FormKTP extends javax.swing.JFrame {

    /**
     * Creates new form KTP
     */
    public FormKTP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGroupJKel = new javax.swing.ButtonGroup();
        BGroupWN = new javax.swing.ButtonGroup();
        jFileChooser1 = new javax.swing.JFileChooser();
        FORMKTP = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Body = new javax.swing.JPanel();
        Merah = new javax.swing.JPanel();
        Putih = new javax.swing.JPanel();
        Formulir = new javax.swing.JPanel();
        Lnama = new javax.swing.JLabel();
        Lttl = new javax.swing.JLabel();
        Lalamat = new javax.swing.JLabel();
        Ldesa = new javax.swing.JLabel();
        Ljkel = new javax.swing.JLabel();
        Lrtrw = new javax.swing.JLabel();
        TFnama = new javax.swing.JTextField();
        TFtempat = new javax.swing.JTextField();
        RBlaki = new javax.swing.JRadioButton();
        RBwanita = new javax.swing.JRadioButton();
        TFalamat = new javax.swing.JTextField();
        Lcamat = new javax.swing.JLabel();
        Lagama = new javax.swing.JLabel();
        Lstatus = new javax.swing.JLabel();
        Lgoldar = new javax.swing.JLabel();
        Lkerja = new javax.swing.JLabel();
        Lwarga = new javax.swing.JLabel();
        TFkerja = new javax.swing.JTextField();
        TFrt = new javax.swing.JTextField();
        TFdesa = new javax.swing.JTextField();
        TFcamat = new javax.swing.JTextField();
        CBagama = new javax.swing.JComboBox<>();
        CBstatus = new javax.swing.JComboBox<>();
        CBgoldar = new javax.swing.JComboBox<>();
        RBwni = new javax.swing.JRadioButton();
        RBwna = new javax.swing.JRadioButton();
        TFrw = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        PanelFoto = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        LFoto = new javax.swing.JLabel();
        TFtgl = new javax.swing.JTextField();
        BTNdetail = new javax.swing.JButton();
        BTNtampil = new javax.swing.JButton();
        BTNhapus = new javax.swing.JButton();
        BTNexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form Kartu Tanda Penduduk (KTP)");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        FORMKTP.setPreferredSize(new java.awt.Dimension(679, 689));

        Header.setBackground(new java.awt.Color(39, 72, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM KARTU TANDA PENDUDUK");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("REPUBLIK INDONESIA");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1))
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        Body.setBackground(new java.awt.Color(115, 187, 255));

        Merah.setBackground(new java.awt.Color(255, 0, 0));
        Merah.setPreferredSize(new java.awt.Dimension(0, 5));

        javax.swing.GroupLayout MerahLayout = new javax.swing.GroupLayout(Merah);
        Merah.setLayout(MerahLayout);
        MerahLayout.setHorizontalGroup(
            MerahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        MerahLayout.setVerticalGroup(
            MerahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        Putih.setBackground(new java.awt.Color(255, 255, 255));
        Putih.setPreferredSize(new java.awt.Dimension(0, 5));

        javax.swing.GroupLayout PutihLayout = new javax.swing.GroupLayout(Putih);
        Putih.setLayout(PutihLayout);
        PutihLayout.setHorizontalGroup(
            PutihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PutihLayout.setVerticalGroup(
            PutihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        Formulir.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "FORM ISIAN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        Formulir.setOpaque(false);

        Lnama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lnama.setText("Nama");

        Lttl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lttl.setText("Tempat / TGL Lahir");

        Lalamat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lalamat.setText("Alamat");

        Ldesa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Ldesa.setText("Kel / Desa");

        Ljkel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Ljkel.setText("Jenis Kelamin");

        Lrtrw.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lrtrw.setText("RT / RW");

        TFnama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        TFtempat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        BGroupJKel.add(RBlaki);
        RBlaki.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RBlaki.setText("Laki-laki");
        RBlaki.setOpaque(false);

        BGroupJKel.add(RBwanita);
        RBwanita.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RBwanita.setText("Perempuan");
        RBwanita.setOpaque(false);

        TFalamat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Lcamat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lcamat.setText("Kecamatan");

        Lagama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lagama.setText("Agama");

        Lstatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lstatus.setText("Status Perkawinan");

        Lgoldar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lgoldar.setText("Gol. Darah");

        Lkerja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lkerja.setText("Pekerjaan");

        Lwarga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lwarga.setText("Kewarganegaraan");

        TFkerja.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        TFrt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        TFdesa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        TFcamat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        CBagama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CBagama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kristen", "Katholik", "Islam", "Hindu", "Budha", "Konghucu" }));

        CBstatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CBstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum Kawin", "Kawin", "Cerai Hidup", "Cerai Mati" }));

        CBgoldar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CBgoldar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "AB", "O" }));

        BGroupWN.add(RBwni);
        RBwni.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RBwni.setText("WNI");
        RBwni.setOpaque(false);

        BGroupWN.add(RBwna);
        RBwna.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RBwna.setText("WNA");
        RBwna.setOpaque(false);

        TFrw.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("/");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("/");

        PanelFoto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Foto Ukuran 3 x 4", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        PanelFoto.setOpaque(false);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/photography.png"))); // NOI18N
        jButton1.setText("Pilih Foto");
        jButton1.setToolTipText("");
        jButton1.setFocusPainted(false);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        LFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LFoto.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(24, 114, 253), null));

        javax.swing.GroupLayout PanelFotoLayout = new javax.swing.GroupLayout(PanelFoto);
        PanelFoto.setLayout(PanelFotoLayout);
        PanelFotoLayout.setHorizontalGroup(
            PanelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFotoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFotoLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(36, 36, 36))
                    .addComponent(LFoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        PanelFotoLayout.setVerticalGroup(
            PanelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFotoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addGap(16, 16, 16)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        TFtgl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout FormulirLayout = new javax.swing.GroupLayout(Formulir);
        Formulir.setLayout(FormulirLayout);
        FormulirLayout.setHorizontalGroup(
            FormulirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormulirLayout.createSequentialGroup()
                .addGroup(FormulirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormulirLayout.createSequentialGroup()
                        .addGroup(FormulirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(FormulirLayout.createSequentialGroup()
                                .addGroup(FormulirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(FormulirLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(FormulirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Lnama)
                                            .addComponent(Lttl)
                                            .addComponent(Ljkel)
                                            .addComponent(Lalamat)))
                                    .addGroup(FormulirLayout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addGroup(FormulirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Ldesa)
                                            .addComponent(Lrtrw)
                                            .addComponent(Lcamat)))
                                    .addGroup(FormulirLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(Lagama))
                                    .addGroup(FormulirLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(Lstatus)))
                                .addGap(24, 24, 24)
                                .addGroup(FormulirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(FormulirLayout.createSequentialGroup()
                                        .addComponent(TFrt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TFrw, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(CBagama, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CBstatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(FormulirLayout.createSequentialGroup()
                                        .addComponent(RBlaki)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RBwanita))
                                    .addGroup(FormulirLayout.createSequentialGroup()
                                        .addComponent(TFtempat, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TFtgl, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TFnama, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TFcamat)
                                    .addComponent(TFdesa)
                                    .addComponent(TFalamat, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)))
                            .addGroup(FormulirLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(FormulirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lwarga)
                                    .addComponent(Lkerja))
                                .addGap(32, 32, 32)
                                .addGroup(FormulirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(FormulirLayout.createSequentialGroup()
                                        .addComponent(RBwni)
                                        .addGap(10, 10, 10)
                                        .addComponent(RBwna))
                                    .addComponent(CBgoldar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TFkerja, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addComponent(PanelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FormulirLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Lgoldar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FormulirLayout.setVerticalGroup(
            FormulirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormulirLayout.createSequentialGroup()
                .addGroup(FormulirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormulirLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Lnama))
                    .addGroup(FormulirLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TFnama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FormulirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormulirLayout.createSequentialGroup()
                        .addGroup(FormulirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFtgl, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                            .addComponent(TFtempat)
                            .addComponent(Lttl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14))
                    .addGroup(FormulirLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(FormulirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ljkel)
                    .addComponent(RBlaki)
                    .addComponent(RBwanita))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FormulirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TFalamat, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(Lalamat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FormulirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lrtrw)
                    .addComponent(TFrt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFrw, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormulirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFdesa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ldesa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormulirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFcamat, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lcamat))
                .addGap(18, 18, 18)
                .addGroup(FormulirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CBagama, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(Lagama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FormulirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CBstatus, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(Lstatus, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FormulirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lgoldar)
                    .addComponent(CBgoldar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FormulirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lkerja)
                    .addComponent(TFkerja, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FormulirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lwarga)
                    .addComponent(RBwni)
                    .addComponent(RBwna))
                .addGap(20, 20, 20))
            .addGroup(FormulirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BTNdetail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNdetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/zoom.png"))); // NOI18N
        BTNdetail.setText("Lihat Detail");
        BTNdetail.setToolTipText("");
        BTNdetail.setFocusPainted(false);
        BTNdetail.setOpaque(false);
        BTNdetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNdetailActionPerformed(evt);
            }
        });

        BTNtampil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNtampil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/print.png"))); // NOI18N
        BTNtampil.setText("Cetak KTP");
        BTNtampil.setToolTipText("");
        BTNtampil.setFocusPainted(false);
        BTNtampil.setOpaque(false);
        BTNtampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNtampilActionPerformed(evt);
            }
        });

        BTNhapus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/busy.png"))); // NOI18N
        BTNhapus.setText("Ulangi");
        BTNhapus.setToolTipText("");
        BTNhapus.setFocusPainted(false);
        BTNhapus.setOpaque(false);
        BTNhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNhapusActionPerformed(evt);
            }
        });

        BTNexit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BTNexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sign-out.png"))); // NOI18N
        BTNexit.setText("Keluar");
        BTNexit.setToolTipText("");
        BTNexit.setFocusPainted(false);
        BTNexit.setOpaque(false);
        BTNexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BodyLayout = new javax.swing.GroupLayout(Body);
        Body.setLayout(BodyLayout);
        BodyLayout.setHorizontalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Merah, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
            .addComponent(Putih, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BodyLayout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addComponent(BTNtampil)
                .addGap(18, 18, 18)
                .addComponent(BTNdetail)
                .addGap(18, 18, 18)
                .addComponent(BTNhapus)
                .addGap(18, 18, 18)
                .addComponent(BTNexit)
                .addGap(90, 90, 90))
            .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BodyLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Formulir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        BodyLayout.setVerticalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Merah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Putih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 539, Short.MAX_VALUE)
                .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNdetail, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNtampil, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNexit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
            .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BodyLayout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(Formulir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(64, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout FORMKTPLayout = new javax.swing.GroupLayout(FORMKTP);
        FORMKTP.setLayout(FORMKTPLayout);
        FORMKTPLayout.setHorizontalGroup(
            FORMKTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FORMKTPLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(FORMKTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Body, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        FORMKTPLayout.setVerticalGroup(
            FORMKTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FORMKTPLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(FORMKTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(FORMKTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNdetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNdetailActionPerformed
        // TODO add your handling code here:
        String nama,tempat,tanggal,jk=null,alamat,rt,rw,desa,camat,agama,status,goldar,kerja,warga=null;
        ImageIcon icon = null;
        nama = TFnama.getText();
        tempat = TFtempat.getText();
        tanggal = TFtgl.getText();
        
        if(RBlaki.isSelected()){
            jk = RBlaki.getText();
        }else if(RBwanita.isSelected()){
         jk = RBwanita.getText();   
        }
        alamat = TFalamat.getText();
        rt = TFrt.getText();
        rw = TFrw.getText();
        desa = TFdesa.getText();
        camat = TFcamat.getText();
        
        agama = CBagama.getSelectedItem().toString();
        status = CBstatus.getSelectedItem().toString();
        goldar = CBgoldar.getSelectedItem().toString();
        kerja = TFkerja.getText();
        
        if(RBwni.isSelected()){
            warga = RBwni.getText();
        }else if(RBwna.isSelected()){
         warga = RBwna.getText();   
        }
  
        JOptionPane.showMessageDialog(this,
                                           "Nama : " +nama+"\n"+ 
                                           "TTL: "+tempat+" "+tanggal+"\n"+
                                           "Jenis Kelamin : "+jk+"\n"+
                                           "Alamat : "+alamat+"\n"+
                                           "RT/RW : "+rt+"/"+rw+"\n"+
                                           "Kel/Desa : "+desa+"\n"+
                                           "Kecamatan : "+camat+"\n"+
                                           "Agama : "+agama+"\n"+
                                           "Status : "+status+"\n"+
                                           "Goldar : "+goldar+"\n"+
                                           "Pekerjaan : "+kerja+"\n"+
                                           "Kewarganeegaraan : "+warga);
 
    }//GEN-LAST:event_BTNdetailActionPerformed

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser OPEN = new JFileChooser();
        int returnVal = OPEN.showOpenDialog(null);

        File filegambar = null;
        if(returnVal == JFileChooser.APPROVE_OPTION){
            filegambar = OPEN.getSelectedFile();
            String filename = filegambar.getAbsolutePath();

        }
        try{
            BufferedImage gambar=ImageIO.read(filegambar);
            ImageIcon icon=new ImageIcon(gambar.getScaledInstance(175, 230,0));
            LFoto.setIcon(icon);
        }
        catch(IOException e) {e.getMessage();}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BTNhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNhapusActionPerformed
        // TODO add your handling code here:
        TFnama.setText("");
        TFtempat.setText("");
        TFtgl.setText("");
        TFalamat.setText("");
        TFrt.setText("");
        TFrw.setText("");
        TFdesa.setText("");
        TFcamat.setText("");
        TFkerja.setText("");
        BGroupJKel.clearSelection();
        BGroupWN.clearSelection();
        TFtgl.setText("");
        TFtgl.setText("");
    }//GEN-LAST:event_BTNhapusActionPerformed

    private void BTNexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_BTNexitActionPerformed

    private void BTNtampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNtampilActionPerformed
        // TODO add your handling code here:
//        new KTP().setVisible(true);
        KTP p = new KTP();
        KTP.Hnama.setText(this.TFnama.getText());
        KTP.Htempat.setText(this.TFtempat.getText());
        KTP.Htanggal.setText(this.TFtgl.getText());
        
        if(RBlaki.isSelected()){
            KTP.Hjkel.setText(RBlaki.getText());
        }else if(RBwanita.isSelected()){
            KTP.Hjkel.setText(RBwanita.getText());
        }
        
        KTP.Halamat.setText(this.TFalamat.getText());
        KTP.Hrt.setText(this.TFrt.getText());
        KTP.Hrw.setText(this.TFrw.getText());
        KTP.Hdesa.setText(this.TFdesa.getText());
        KTP.Hcamat.setText(this.TFcamat.getText());
        KTP.Hagama.setText(this.CBagama.getSelectedItem().toString());
        KTP.Hstatus.setText(this.CBstatus.getSelectedItem().toString());
        KTP.Hgoldar.setText(this.CBgoldar.getSelectedItem().toString());
        KTP.Hkerja.setText(this.TFkerja.getText());
        
        if(RBwni.isSelected()){
            KTP.Hwarga.setText(RBwni.getText());
        }else if(RBwna.isSelected()){
            KTP.Hwarga.setText(RBwna.getText());
        }
        KTP.HFoto.setIcon(this.LFoto.getIcon());
        p.setVisible(true);
    }//GEN-LAST:event_BTNtampilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKTP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKTP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGroupJKel;
    private javax.swing.ButtonGroup BGroupWN;
    private javax.swing.JButton BTNdetail;
    private javax.swing.JButton BTNexit;
    private javax.swing.JButton BTNhapus;
    public javax.swing.JButton BTNtampil;
    private javax.swing.JPanel Body;
    private javax.swing.JComboBox<String> CBagama;
    private javax.swing.JComboBox<String> CBgoldar;
    private javax.swing.JComboBox<String> CBstatus;
    private javax.swing.JPanel FORMKTP;
    private javax.swing.JPanel Formulir;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel LFoto;
    private javax.swing.JLabel Lagama;
    private javax.swing.JLabel Lalamat;
    private javax.swing.JLabel Lcamat;
    private javax.swing.JLabel Ldesa;
    private javax.swing.JLabel Lgoldar;
    private javax.swing.JLabel Ljkel;
    private javax.swing.JLabel Lkerja;
    private javax.swing.JLabel Lnama;
    private javax.swing.JLabel Lrtrw;
    private javax.swing.JLabel Lstatus;
    private javax.swing.JLabel Lttl;
    private javax.swing.JLabel Lwarga;
    private javax.swing.JPanel Merah;
    private javax.swing.JPanel PanelFoto;
    private javax.swing.JPanel Putih;
    private javax.swing.JRadioButton RBlaki;
    private javax.swing.JRadioButton RBwanita;
    private javax.swing.JRadioButton RBwna;
    private javax.swing.JRadioButton RBwni;
    public javax.swing.JTextField TFalamat;
    private javax.swing.JTextField TFcamat;
    private javax.swing.JTextField TFdesa;
    private javax.swing.JTextField TFkerja;
    private javax.swing.JTextField TFnama;
    private javax.swing.JTextField TFrt;
    private javax.swing.JTextField TFrw;
    private javax.swing.JTextField TFtempat;
    private javax.swing.JTextField TFtgl;
    private javax.swing.JButton jButton1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
