/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tugas_3;

/**
 *
 * @author Miechel
 */
public class SIA_UNMUL extends javax.swing.JFrame {

    /**
     * Creates new form SIA_UNMUL
     */
    public SIA_UNMUL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelAtas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        panelIsi = new javax.swing.JPanel();
        panelMenuSIA = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnDosen = new javax.swing.JButton();
        btnMhs = new javax.swing.JButton();
        btnKrs = new javax.swing.JButton();
        btnJadwal = new javax.swing.JButton();
        panelKonten = new javax.swing.JPanel();
        siadosen = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelMenuDosen = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        panelSIAdosen = new javax.swing.JPanel();
        fotoAwal = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        menu1 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        menu2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        menu3 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        menu4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        menu5 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        menu6 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        siamahasiswa = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelJurusan = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        panelDetilJurusan = new javax.swing.JPanel();
        TI = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        IK = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane6 = new javax.swing.JTextPane();
        krs = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        TFnim = new javax.swing.JTextField();
        TFnama = new javax.swing.JTextField();
        CBtahun = new javax.swing.JComboBox<>();
        CBkelas = new javax.swing.JComboBox<>();
        CBsms = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TKRS = new javax.swing.JTextArea();
        jLabel35 = new javax.swing.JLabel();
        TFmk = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jadwal = new javax.swing.JPanel();
        judul = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        scrollTI = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        scroolIK = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        panelFooter = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Informasi Akademik FKTI");
        setMinimumSize(new java.awt.Dimension(1250, 730));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        panelAtas.setBackground(new java.awt.Color(197, 0, 23));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tugas_3/Unmul.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SISTEM INFORMASI AKADEMIK");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("FAKULTAS ILMU KOMPUTER DAN TEKNOLOGI INFORMASI");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("UNIVERSITAS MULAWARMAN");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Jalan Barong Tongok No.01 Kampus Gunung Kelua, Telp : 0541-137137, email : fkti@unmul.ac.id, website : fkti.unmul.ac.id");

        javax.swing.GroupLayout panelAtasLayout = new javax.swing.GroupLayout(panelAtas);
        panelAtas.setLayout(panelAtasLayout);
        panelAtasLayout.setHorizontalGroup(
            panelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAtasLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(panelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addContainerGap(624, Short.MAX_VALUE))
        );
        panelAtasLayout.setVerticalGroup(
            panelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAtasLayout.createSequentialGroup()
                .addGroup(panelAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAtasLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(panelAtasLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel19)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21)))
                .addContainerGap())
        );

        getContentPane().add(panelAtas, java.awt.BorderLayout.PAGE_START);

        panelIsi.setBackground(new java.awt.Color(255, 188, 188));

        panelMenuSIA.setBackground(new java.awt.Color(197, 0, 23));
        panelMenuSIA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelMenuSIA.setFocusable(false);
        panelMenuSIA.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        panelMenuSIA.setPreferredSize(new java.awt.Dimension(603, 45));
        panelMenuSIA.setLayout(new javax.swing.BoxLayout(panelMenuSIA, javax.swing.BoxLayout.LINE_AXIS));

        btnHome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home.png"))); // NOI18N
        btnHome.setFocusPainted(false);
        btnHome.setFocusable(false);
        btnHome.setMaximumSize(new java.awt.Dimension(40, 35));
        btnHome.setOpaque(false);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        panelMenuSIA.add(btnHome);

        btnDosen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDosen.setText("SIA DOSEN");
        btnDosen.setFocusPainted(false);
        btnDosen.setFocusable(false);
        btnDosen.setMaximumSize(new java.awt.Dimension(110, 35));
        btnDosen.setOpaque(false);
        btnDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDosenActionPerformed(evt);
            }
        });
        panelMenuSIA.add(btnDosen);

        btnMhs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMhs.setText("SIA MAHASISWA");
        btnMhs.setFocusPainted(false);
        btnMhs.setFocusable(false);
        btnMhs.setMaximumSize(new java.awt.Dimension(150, 35));
        btnMhs.setMinimumSize(new java.awt.Dimension(150, 0));
        btnMhs.setOpaque(false);
        btnMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMhsActionPerformed(evt);
            }
        });
        panelMenuSIA.add(btnMhs);

        btnKrs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnKrs.setText("KRS ONLINE");
        btnKrs.setFocusPainted(false);
        btnKrs.setFocusable(false);
        btnKrs.setMaximumSize(new java.awt.Dimension(130, 35));
        btnKrs.setMinimumSize(new java.awt.Dimension(130, 0));
        btnKrs.setOpaque(false);
        btnKrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKrsActionPerformed(evt);
            }
        });
        panelMenuSIA.add(btnKrs);

        btnJadwal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnJadwal.setText("JADWAL KULIAH");
        btnJadwal.setFocusPainted(false);
        btnJadwal.setFocusable(false);
        btnJadwal.setMaximumSize(new java.awt.Dimension(150, 35));
        btnJadwal.setMinimumSize(new java.awt.Dimension(150, 0));
        btnJadwal.setOpaque(false);
        btnJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalActionPerformed(evt);
            }
        });
        panelMenuSIA.add(btnJadwal);

        panelKonten.setLayout(new java.awt.CardLayout());

        siadosen.setBackground(new java.awt.Color(251, 251, 251));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Selamat Datang di Sistem Informasi Akademik untuk Dosen");

        panelMenuDosen.setLayout(new java.awt.GridLayout(3, 2, 5, 5));

        jPanel11.setBackground(new java.awt.Color(255, 153, 0));
        jPanel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel11.setMaximumSize(new java.awt.Dimension(110, 70));
        jPanel11.setPreferredSize(new java.awt.Dimension(110, 70));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel11MousePressed(evt);
            }
        });
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ISI DATA");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel11.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 200, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("MAHASISWA");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel11.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, -1));

        panelMenuDosen.add(jPanel11);

        jPanel12.setBackground(new java.awt.Color(238, 68, 68));
        jPanel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel12.setMaximumSize(new java.awt.Dimension(110, 70));
        jPanel12.setPreferredSize(new java.awt.Dimension(110, 70));
        jPanel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel12MousePressed(evt);
            }
        });
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("MAHASISWA");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel12.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 52, 200, 20));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("ISI NILAI");
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel12.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 200, -1));

        panelMenuDosen.add(jPanel12);

        jPanel13.setBackground(new java.awt.Color(54, 162, 252));
        jPanel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel13.setMaximumSize(new java.awt.Dimension(110, 70));
        jPanel13.setPreferredSize(new java.awt.Dimension(110, 70));
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel13MousePressed(evt);
            }
        });
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("MAHASISWA");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel13.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 200, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("CEK NILAI");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel13.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 200, -1));

        panelMenuDosen.add(jPanel13);

        jPanel14.setBackground(new java.awt.Color(255, 153, 0));
        jPanel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel14.setMaximumSize(new java.awt.Dimension(110, 70));
        jPanel14.setPreferredSize(new java.awt.Dimension(110, 70));
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel14MousePressed(evt);
            }
        });
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("KULIAH");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel14.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 130, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("INPUT JADWAL");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel14.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 200, -1));

        panelMenuDosen.add(jPanel14);

        jPanel15.setBackground(new java.awt.Color(208, 63, 0));
        jPanel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel15.setMaximumSize(new java.awt.Dimension(110, 70));
        jPanel15.setPreferredSize(new java.awt.Dimension(110, 70));
        jPanel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel15MousePressed(evt);
            }
        });
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("MAHASISWA");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel15.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 200, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("CARI DATA");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel15.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 200, -1));

        panelMenuDosen.add(jPanel15);

        jPanel17.setBackground(new java.awt.Color(0, 175, 42));
        jPanel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel17.setMaximumSize(new java.awt.Dimension(110, 70));
        jPanel17.setPreferredSize(new java.awt.Dimension(110, 70));
        jPanel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel17MousePressed(evt);
            }
        });
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("MATA KULIAH");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel17.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 200, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("INPUT");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel17.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 200, -1));

        panelMenuDosen.add(jPanel17);

        panelSIAdosen.setLayout(new java.awt.CardLayout());

        fotoAwal.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tugas_3/FKTI.jpg"))); // NOI18N

        javax.swing.GroupLayout fotoAwalLayout = new javax.swing.GroupLayout(fotoAwal);
        fotoAwal.setLayout(fotoAwalLayout);
        fotoAwalLayout.setHorizontalGroup(
            fotoAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 737, Short.MAX_VALUE)
        );
        fotoAwalLayout.setVerticalGroup(
            fotoAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 425, Short.MAX_VALUE)
        );

        panelSIAdosen.add(fotoAwal, "card3");

        menu1.setBackground(new java.awt.Color(255, 241, 180));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel27.setText("MENU 1 DOSEN");

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel36.setText("PANEL ISI DATA MAHASISWA");

        javax.swing.GroupLayout menu1Layout = new javax.swing.GroupLayout(menu1);
        menu1.setLayout(menu1Layout);
        menu1Layout.setHorizontalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu1Layout.createSequentialGroup()
                .addGroup(menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menu1Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel36))
                    .addGroup(menu1Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel27)))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        menu1Layout.setVerticalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu1Layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel36)
                .addGap(131, 131, 131))
        );

        panelSIAdosen.add(menu1, "card3");

        menu2.setBackground(new java.awt.Color(255, 153, 153));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel24.setText("MENU 2 DOSEN");

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel37.setText("PANEL ISI NILAI MAHASISWA");

        javax.swing.GroupLayout menu2Layout = new javax.swing.GroupLayout(menu2);
        menu2.setLayout(menu2Layout);
        menu2Layout.setHorizontalGroup(
            menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu2Layout.createSequentialGroup()
                .addGroup(menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menu2Layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jLabel24))
                    .addGroup(menu2Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel37)))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        menu2Layout.setVerticalGroup(
            menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu2Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        panelSIAdosen.add(menu2, "card4");

        menu3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel25.setText("MENU 3 DOSEN");

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel38.setText("PANEL CEK NILAI MAHASISWA");

        javax.swing.GroupLayout menu3Layout = new javax.swing.GroupLayout(menu3);
        menu3.setLayout(menu3Layout);
        menu3Layout.setHorizontalGroup(
            menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu3Layout.createSequentialGroup()
                .addContainerGap(210, Short.MAX_VALUE)
                .addGroup(menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu3Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(91, 91, 91)))
                .addGap(200, 200, 200))
        );
        menu3Layout.setVerticalGroup(
            menu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu3Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel38)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        panelSIAdosen.add(menu3, "card5");

        menu4.setBackground(new java.awt.Color(255, 241, 180));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel26.setText("MENU 4 DOSEN");

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel39.setText("PANEL INPUT JADWAL MATA KULIAH");

        javax.swing.GroupLayout menu4Layout = new javax.swing.GroupLayout(menu4);
        menu4.setLayout(menu4Layout);
        menu4Layout.setHorizontalGroup(
            menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu4Layout.createSequentialGroup()
                .addGroup(menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menu4Layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jLabel26))
                    .addGroup(menu4Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel39)))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        menu4Layout.setVerticalGroup(
            menu4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu4Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel39)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        panelSIAdosen.add(menu4, "card6");

        menu5.setBackground(new java.awt.Color(249, 222, 199));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel28.setText("MENU 5 DOSEN");

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel40.setText("PANEL CARI DATA MAHASISWA");

        javax.swing.GroupLayout menu5Layout = new javax.swing.GroupLayout(menu5);
        menu5.setLayout(menu5Layout);
        menu5Layout.setHorizontalGroup(
            menu5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu5Layout.createSequentialGroup()
                .addGroup(menu5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menu5Layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jLabel28))
                    .addGroup(menu5Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel40)))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        menu5Layout.setVerticalGroup(
            menu5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu5Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel40)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        panelSIAdosen.add(menu5, "card7");

        menu6.setBackground(new java.awt.Color(211, 255, 216));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel29.setText("MENU 6 DOSEN");

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel41.setText("PANEL INPUT MATA KULIAH");

        javax.swing.GroupLayout menu6Layout = new javax.swing.GroupLayout(menu6);
        menu6.setLayout(menu6Layout);
        menu6Layout.setHorizontalGroup(
            menu6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu6Layout.createSequentialGroup()
                .addContainerGap(228, Short.MAX_VALUE)
                .addGroup(menu6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu6Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(75, 75, 75)))
                .addGap(207, 207, 207))
        );
        menu6Layout.setVerticalGroup(
            menu6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu6Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel41)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        panelSIAdosen.add(menu6, "card8");

        javax.swing.GroupLayout siadosenLayout = new javax.swing.GroupLayout(siadosen);
        siadosen.setLayout(siadosenLayout);
        siadosenLayout.setHorizontalGroup(
            siadosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siadosenLayout.createSequentialGroup()
                .addGroup(siadosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(siadosenLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addGroup(siadosenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelSIAdosen, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(panelMenuDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(295, Short.MAX_VALUE))
        );
        siadosenLayout.setVerticalGroup(
            siadosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siadosenLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(siadosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(siadosenLayout.createSequentialGroup()
                        .addComponent(panelMenuDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 75, Short.MAX_VALUE))
                    .addComponent(panelSIAdosen, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelKonten.add(siadosen, "card3");

        siamahasiswa.setBackground(new java.awt.Color(251, 251, 251));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Selamat Datang di Sistem Informasi Akademik untuk Mahasiswa");

        panelJurusan.setLayout(new java.awt.GridBagLayout());

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Teknik Informatika");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 37;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 11, 0);
        panelJurusan.add(jButton3, gridBagConstraints);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Ilmu Komputer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 37;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 11, 10);
        panelJurusan.add(jButton4, gridBagConstraints);

        panelDetilJurusan.setLayout(new java.awt.CardLayout());

        TI.setBackground(new java.awt.Color(255, 211, 211));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel42.setText("Sejarah Program Studi Teknik Informatika");

        jTextPane5.setBackground(new java.awt.Color(255, 211, 211));
        jTextPane5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextPane5.setText("Teknik Informatika adalah salah satu jurusan di Fakultas Ilmu Komputer dan Teknologi Informasi.\nTeknik Informatika berdiri sejak tahun 2010.\nTotal mahasiswa aktif sampai tahun akademik 2016/2017 sebanyak 1321 mahasiswa.\nJumlah dosen pengajar sebanyak 25 dosen dengan jenjang pendidikan S2 dan S3.\nJumlah ruang kuliah sebanyak 10 ruang dan laboratorium sebanyak 4 ruang.");
        jScrollPane4.setViewportView(jTextPane5);

        javax.swing.GroupLayout TILayout = new javax.swing.GroupLayout(TI);
        TI.setLayout(TILayout);
        TILayout.setHorizontalGroup(
            TILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TILayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(TILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        TILayout.setVerticalGroup(
            TILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TILayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        panelDetilJurusan.add(TI, "card2");

        IK.setBackground(new java.awt.Color(189, 229, 255));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel43.setText("Sejarah Program Studi Ilmu Komputer");

        jTextPane6.setBackground(new java.awt.Color(189, 229, 255));
        jTextPane6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextPane6.setText("Ilmu Komputer adalah salah satu jurusan di Fakultas Ilmu Komputer dan Teknologi Informasi.\nImu Komputer berdiri sejak tahun 2004.\nTotal mahasiswa aktif sampai tahun akademik 2016/2017 sebanyak 400 mahasiswa.\nJumlah dosen pengajar sebanyak 15 dosen dengan jenjang pendidikan S2 dan S3.\nJumlah ruang kuliah sebanyak 10 ruang dan laboratorium sebanyak 4 ruang.");
        jScrollPane5.setViewportView(jTextPane6);

        javax.swing.GroupLayout IKLayout = new javax.swing.GroupLayout(IK);
        IK.setLayout(IKLayout);
        IKLayout.setHorizontalGroup(
            IKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IKLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(IKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        IKLayout.setVerticalGroup(
            IKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IKLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        panelDetilJurusan.add(IK, "card3");

        javax.swing.GroupLayout siamahasiswaLayout = new javax.swing.GroupLayout(siamahasiswa);
        siamahasiswa.setLayout(siamahasiswaLayout);
        siamahasiswaLayout.setHorizontalGroup(
            siamahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siamahasiswaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(siamahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(siamahasiswaLayout.createSequentialGroup()
                        .addComponent(panelJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(panelDetilJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(279, Short.MAX_VALUE))
        );
        siamahasiswaLayout.setVerticalGroup(
            siamahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siamahasiswaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addGap(38, 38, 38)
                .addGroup(siamahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelDetilJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelKonten.add(siamahasiswa, "card4");

        krs.setBackground(new java.awt.Color(251, 251, 251));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("SISTEM KRS (Kartu Rencana Studi) ONLINE");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText("Angkatan");

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("NIM");

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText("Semester");

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("Nama");

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setText("Kelas");

        TFnim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        TFnama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        CBtahun.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CBtahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2016", "2015", "2014", "2013" }));

        CBkelas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CBkelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kelas", "TI A", "TI B", "TI C", "TI D", "TI E", "ILKOM A", "ILKOM B" }));

        CBsms.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CBsms.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Semester", "1", "2", "3", "4", "5", "6", "7", "8" }));
        CBsms.setPreferredSize(new java.awt.Dimension(111, 29));

        TKRS.setEditable(false);
        TKRS.setColumns(20);
        TKRS.setRows(5);
        jScrollPane1.setViewportView(TKRS);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setText("Mata Kuliah");

        TFmk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("SIMPAN KRS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("HAPUS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout krsLayout = new javax.swing.GroupLayout(krs);
        krs.setLayout(krsLayout);
        krsLayout.setHorizontalGroup(
            krsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(krsLayout.createSequentialGroup()
                .addGroup(krsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(krsLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(krsLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(krsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(krsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBkelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBsms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFnim, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFnama, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBtahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFmk, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(krsLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(322, Short.MAX_VALUE))
        );
        krsLayout.setVerticalGroup(
            krsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(krsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(krsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(krsLayout.createSequentialGroup()
                        .addGroup(krsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(krsLayout.createSequentialGroup()
                                .addComponent(TFnim, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(krsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFnama, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(krsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CBtahun, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(krsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CBkelas, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(krsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CBsms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(krsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                            .addComponent(TFmk, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(krsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(159, 159, 159))
                    .addGroup(krsLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        panelKonten.add(krs, "card5");

        jadwal.setBackground(new java.awt.Color(251, 251, 251));

        judul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        judul.setText("Selamat Datang di menu jadwal mata kuliah");

        jTextPane2.setBackground(new java.awt.Color(248, 248, 248));
        jTextPane2.setText(" Jadwal Mata Kuliah Program Studi Teknik Informatika Semester Genap 2016/2017\n Senin     : 406 (08.30 - 11.00) Pemograman Framework \n              : 406 (08.30 - 11.00) Pemograman Visual\n              : 406 (08.30 - 11.00) Pemograman Basis Data\n\n Selasa   : 406 (08.30 - 11.00) Etika dan Profesionalitas Informatika\n              : 406 (08.30 - 11.00) Pemograman Web lanjutan\n              : 406 (08.30 - 11.00) Technopreneurship \n\n Rabu    : 406 (08.30 - 11.00) Pemograman Framework \n             : 406 (08.30 - 11.00) Pemograman Visual\n             : 406 (08.30 - 11.00) Pemograman Basis Data\n\n Kamis   : 406 (08.30 - 11.00) Etika dan Profesionalitas Informatika\n             : 406 (08.30 - 11.00) Pemograman Web lanjutan\n             : 406 (08.30 - 11.00) Technopreneurship ");
        scrollTI.setViewportView(jTextPane2);

        jTabbedPane1.addTab("Teknik Informatika", scrollTI);

        jTextPane3.setBackground(new java.awt.Color(248, 248, 248));
        jTextPane3.setText(" Jadwal Mata Kuliah Program Studi Ilmu Komputer Semester Genap 2016/2017\n Senin     : 406 (08.30 - 11.00) Pemograman Framework \n                 406 (08.30 - 11.00) Pemograman Visual\n                 406 (08.30 - 11.00) Pemograman Basis Data\n\n Selasa   : 406 (08.30 - 11.00) Etika dan Profesionalitas Informatika\n                 406 (08.30 - 11.00) Pemograman Web lanjutan\n                 406 (08.30 - 11.00) Technopreneurship ");
        scroolIK.setViewportView(jTextPane3);

        jTabbedPane1.addTab("Ilmu Komputer", scroolIK);

        jTextPane1.setText(" Jadwal Mata Kuliah Program Studi Teknik Komputer Semester Genap 2016/2017\n Senin     : 406 (08.30 - 11.00) Pemograman Framework \n              : 406 (08.30 - 11.00) Pemograman Visual\n              : 406 (08.30 - 11.00) Pemograman Basis Data\n\n Selasa   : 406 (08.30 - 11.00) Etika dan Profesionalitas Informatika\n              : 406 (08.30 - 11.00) Pemograman Web lanjutan\n              : 406 (08.30 - 11.00) Technopreneurship \n\n Rabu    : 406 (08.30 - 11.00) Pemograman Framework \n             : 406 (08.30 - 11.00) Pemograman Visual\n             : 406 (08.30 - 11.00) Pemograman Basis Data\n\n Kamis   : 406 (08.30 - 11.00) Etika dan Profesionalitas Informatika\n             : 406 (08.30 - 11.00) Pemograman Web lanjutan\n             : 406 (08.30 - 11.00) Technopreneurship ");
        jScrollPane2.setViewportView(jTextPane1);

        jTabbedPane1.addTab("Teknik Komputer", jScrollPane2);

        jTextPane4.setText(" Jadwal Mata Kuliah Program Studi Sistem Informasi Semester Genap 2016/2017\n Senin     : 406 (08.30 - 11.00) Pemograman Framework \n              : 406 (08.30 - 11.00) Pemograman Visual\n              : 406 (08.30 - 11.00) Pemograman Basis Data\n\n Selasa   : 406 (08.30 - 11.00) Etika dan Profesionalitas Informatika\n              : 406 (08.30 - 11.00) Pemograman Web lanjutan\n              : 406 (08.30 - 11.00) Technopreneurship \n\n Rabu    : 406 (08.30 - 11.00) Pemograman Framework \n             : 406 (08.30 - 11.00) Pemograman Visual\n             : 406 (08.30 - 11.00) Pemograman Basis Data\n\n Kamis   : 406 (08.30 - 11.00) Etika dan Profesionalitas Informatika\n             : 406 (08.30 - 11.00) Pemograman Web lanjutan\n             : 406 (08.30 - 11.00) Technopreneurship ");
        jScrollPane3.setViewportView(jTextPane4);

        jTabbedPane1.addTab("Sistem Informasi", jScrollPane3);

        javax.swing.GroupLayout jadwalLayout = new javax.swing.GroupLayout(jadwal);
        jadwal.setLayout(jadwalLayout);
        jadwalLayout.setHorizontalGroup(
            jadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jadwalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(judul)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(555, Short.MAX_VALUE))
        );
        jadwalLayout.setVerticalGroup(
            jadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jadwalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(judul)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        panelKonten.add(jadwal, "card6");

        javax.swing.GroupLayout panelIsiLayout = new javax.swing.GroupLayout(panelIsi);
        panelIsi.setLayout(panelIsiLayout);
        panelIsiLayout.setHorizontalGroup(
            panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIsiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelKonten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMenuSIA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelIsiLayout.setVerticalGroup(
            panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIsiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMenuSIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelKonten, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelIsi, java.awt.BorderLayout.CENTER);

        panelFooter.setBackground(new java.awt.Color(204, 0, 0));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("POSTTEST MODUL 3 PEMOGRAMAN VISUAL");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Develop by : Ferry Miechel Lubis 1515015111");

        javax.swing.GroupLayout panelFooterLayout = new javax.swing.GroupLayout(panelFooter);
        panelFooter.setLayout(panelFooterLayout);
        panelFooterLayout.setHorizontalGroup(
            panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFooterLayout.createSequentialGroup()
                .addContainerGap(750, Short.MAX_VALUE)
                .addGroup(panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFooterLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9))
                    .addComponent(jLabel5))
                .addGap(459, 459, 459))
        );
        panelFooterLayout.setVerticalGroup(
            panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(0, 0, 0)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelFooter, java.awt.BorderLayout.PAGE_END);

        jMenu1.setText("Menu Dosen");

        jMenuItem1.setText("Input Nilai");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Edit Nilai");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Menu Mahasiswa");

        jMenuItem3.setText("Lihat Nilai");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Lihat Rekap Absen");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Informasi");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("About");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Keluar");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu5MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        fotoAwal.setVisible(true);
        siadosen.setVisible(true);
        siamahasiswa.setVisible(false);
        krs.setVisible(false);
        jadwal.setVisible(false);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDosenActionPerformed
        // TODO add your handling code here:
        fotoAwal.setVisible(true);
        siadosen.setVisible(true);
        siamahasiswa.setVisible(false);
        krs.setVisible(false);
        jadwal.setVisible(false);
    }//GEN-LAST:event_btnDosenActionPerformed

    private void btnMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMhsActionPerformed
        // TODO add your handling code here:
        siadosen.setVisible(false);
        siamahasiswa.setVisible(true);
        krs.setVisible(false);
        jadwal.setVisible(false);
    }//GEN-LAST:event_btnMhsActionPerformed

    private void btnKrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKrsActionPerformed
        // TODO add your handling code here:
        siadosen.setVisible(false);
        siamahasiswa.setVisible(false);
        krs.setVisible(true);
        jadwal.setVisible(false);
    }//GEN-LAST:event_btnKrsActionPerformed

    private void btnJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJadwalActionPerformed
        // TODO add your handling code here:
        siadosen.setVisible(false);
        siamahasiswa.setVisible(false);
        krs.setVisible(false);
        jadwal.setVisible(true);
    }//GEN-LAST:event_btnJadwalActionPerformed

    private void jPanel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MousePressed
        // TODO add your handling code here:
        fotoAwal.setVisible(false);
        menu1.setVisible(true);
        menu2.setVisible(false);
        menu3.setVisible(false);
        menu4.setVisible(false);
        menu5.setVisible(false);
        menu6.setVisible(false);
    }//GEN-LAST:event_jPanel11MousePressed

    private void jPanel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MousePressed
        // TODO add your handling code here:
        fotoAwal.setVisible(false);
        menu1.setVisible(false);
        menu2.setVisible(true);
        menu3.setVisible(false);
        menu4.setVisible(false);
        menu5.setVisible(false);
        menu6.setVisible(false);
    }//GEN-LAST:event_jPanel12MousePressed

    private void jPanel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MousePressed
        // TODO add your handling code here:
        fotoAwal.setVisible(false);
        menu1.setVisible(false);
        menu2.setVisible(false);
        menu3.setVisible(true);
        menu4.setVisible(false);
        menu5.setVisible(false);
        menu6.setVisible(false);
    }//GEN-LAST:event_jPanel13MousePressed

    private void jPanel14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MousePressed
        // TODO add your handling code here:
        fotoAwal.setVisible(false);
        menu1.setVisible(false);
        menu2.setVisible(false);
        menu3.setVisible(false);
        menu4.setVisible(true);
        menu5.setVisible(false);
        menu6.setVisible(false);
    }//GEN-LAST:event_jPanel14MousePressed

    private void jPanel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel15MousePressed
        // TODO add your handling code here:
        fotoAwal.setVisible(false);
        menu1.setVisible(false);
        menu2.setVisible(false);
        menu3.setVisible(false);
        menu4.setVisible(false);
        menu5.setVisible(true);
        menu6.setVisible(false);
    }//GEN-LAST:event_jPanel15MousePressed

    private void jPanel17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel17MousePressed
        // TODO add your handling code here:
        fotoAwal.setVisible(false);
        menu1.setVisible(false);
        menu2.setVisible(false);
        menu3.setVisible(false);
        menu4.setVisible(false);
        menu5.setVisible(false);
        menu6.setVisible(true);
    }//GEN-LAST:event_jPanel17MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nim,nama,mk,tahun=null,sms=null,kelas=null;
        nim = TFnim.getText();
        nama = TFnama.getText();
        mk = TFmk.getText();
        tahun = CBtahun.getSelectedItem().toString();
        sms = CBsms.getSelectedItem().toString();
        kelas = CBkelas.getSelectedItem().toString();
        
        TKRS.setText("=================== KRS ONLINE ===================\n"+
                     "= Fakultas Ilmu Komputer dan Teknologi Informasi =\n"+
                     "==================================================\n"+
                     "NIM\t:"+nim+
                     "\nNAMA\t:"+nama+
                     "\nAngkatan\t:"+tahun+
                     "\nSemester\t:"+sms+
                     "\nKelas\t:"+kelas+
                     "\nMata Kuliah\t:"+mk+
                     "\n--------------------------------------------------\n");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        TFnim.setText("");
        TFnama.setText("");
        TFmk.setText("");
        TKRS.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenu5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MousePressed
        // TODO add your handling code here:
        this.dispose();
        new LoginSIA().setVisible(true);
        System.exit(0);
    }//GEN-LAST:event_jMenu5MousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        TI.setVisible(true);
        IK.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        TI.setVisible(false);
        IK.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SIA_UNMUL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SIA_UNMUL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SIA_UNMUL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SIA_UNMUL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SIA_UNMUL().setVisible(false);
                new LoginSIA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBkelas;
    private javax.swing.JComboBox<String> CBsms;
    private javax.swing.JComboBox<String> CBtahun;
    private javax.swing.JPanel IK;
    private javax.swing.JTextField TFmk;
    private javax.swing.JTextField TFnama;
    private javax.swing.JTextField TFnim;
    private javax.swing.JPanel TI;
    private javax.swing.JTextArea TKRS;
    private javax.swing.JButton btnDosen;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnJadwal;
    private javax.swing.JButton btnKrs;
    private javax.swing.JButton btnMhs;
    private javax.swing.JPanel fotoAwal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JTextPane jTextPane6;
    private javax.swing.JPanel jadwal;
    private javax.swing.JLabel judul;
    private javax.swing.JPanel krs;
    private javax.swing.JPanel menu1;
    private javax.swing.JPanel menu2;
    private javax.swing.JPanel menu3;
    private javax.swing.JPanel menu4;
    private javax.swing.JPanel menu5;
    private javax.swing.JPanel menu6;
    private javax.swing.JPanel panelAtas;
    private javax.swing.JPanel panelDetilJurusan;
    private javax.swing.JPanel panelFooter;
    private javax.swing.JPanel panelIsi;
    private javax.swing.JPanel panelJurusan;
    private javax.swing.JPanel panelKonten;
    private javax.swing.JPanel panelMenuDosen;
    private javax.swing.JPanel panelMenuSIA;
    private javax.swing.JPanel panelSIAdosen;
    private javax.swing.JScrollPane scrollTI;
    private javax.swing.JScrollPane scroolIK;
    private javax.swing.JPanel siadosen;
    private javax.swing.JPanel siamahasiswa;
    // End of variables declaration//GEN-END:variables
}
