/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tugas_4;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Miechel
 */
public class FormPelangganLoundry extends javax.swing.JFrame {

    /**
     * Creates new form FormPelangganLoundry
     */
    public FormPelangganLoundry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupPaket = new javax.swing.ButtonGroup();
        FormLoundry = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        panelBody = new javax.swing.JPanel();
        panelDetail = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TFnama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TFtelepon = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TFberat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        panelDetail1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TFtotalharga = new javax.swing.JTextField();
        RBreguler = new javax.swing.JRadioButton();
        RBexpress = new javax.swing.JRadioButton();
        jSlider1 = new javax.swing.JSlider();
        LBpersen = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnProses = new javax.swing.JButton();
        btnUlangi = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        panelNota = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAnota = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("POSTTEST 4 FORM LOUNDRY");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        FormLoundry.setBackground(new java.awt.Color(255, 255, 255));
        FormLoundry.setLayout(new java.awt.BorderLayout());

        panelHeader.setBackground(new java.awt.Color(30, 30, 30));
        panelHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("\"LOUNDRY FERRY\"");
        panelHeader.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FORM PELANGGAN LOUNDRY");
        panelHeader.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 49, -1, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Jalan Pramuka 19 Blok D No. 001 Samarinda");
        panelHeader.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 240, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tugas_4/MesinCuci.png"))); // NOI18N
        panelHeader.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 80, 90));

        FormLoundry.add(panelHeader, java.awt.BorderLayout.PAGE_START);

        panelBody.setBackground(new java.awt.Color(231, 147, 0));
        panelBody.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelDetail.setBackground(new java.awt.Color(167, 96, 0));
        panelDetail.setForeground(new java.awt.Color(66, 66, 66));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama");

        TFnama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TFnama.setText("Masukan Nama Pelanggan");
        TFnama.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TFnamaCaretUpdate(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("No. Telepon");

        TFtelepon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TFtelepon.setText("Masukan No Telepon");
        TFtelepon.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TFteleponCaretUpdate(evt);
            }
        });
        TFtelepon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFteleponKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Berat Cucian (kg)");

        TFberat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TFberat.setText("0");
        TFberat.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TFberatCaretUpdate(evt);
            }
        });
        TFberat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFberatKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("kg");

        jLabel12.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("(  *wajib diisi & format Angka )");

        jLabel13.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("( *wajib diisi )");

        jLabel14.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("( *wajib diisi )");

        javax.swing.GroupLayout panelDetailLayout = new javax.swing.GroupLayout(panelDetail);
        panelDetail.setLayout(panelDetailLayout);
        panelDetailLayout.setHorizontalGroup(
            panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetailLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14))
                    .addComponent(TFtelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDetailLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addComponent(TFnama, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDetailLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13))
                    .addGroup(panelDetailLayout.createSequentialGroup()
                        .addComponent(TFberat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        panelDetailLayout.setVerticalGroup(
            panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetailLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFnama, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFtelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFberat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        panelBody.add(panelDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 13, -1, -1));

        panelDetail1.setBackground(new java.awt.Color(167, 96, 0));
        panelDetail1.setForeground(new java.awt.Color(66, 66, 66));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Besar Diskon");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Jenis Paket Jasa");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total Tarif (Rp)");

        TFtotalharga.setEditable(false);
        TFtotalharga.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        TFtotalharga.setText("0");

        btnGroupPaket.add(RBreguler);
        RBreguler.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        RBreguler.setForeground(new java.awt.Color(255, 255, 255));
        RBreguler.setText("Reguler");
        RBreguler.setOpaque(false);

        btnGroupPaket.add(RBexpress);
        RBexpress.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        RBexpress.setForeground(new java.awt.Color(255, 255, 255));
        RBexpress.setText("Express");
        RBexpress.setOpaque(false);

        jSlider1.setBackground(new java.awt.Color(167, 96, 0));
        jSlider1.setForeground(new java.awt.Color(255, 255, 255));
        jSlider1.setMajorTickSpacing(10);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setToolTipText("");
        jSlider1.setValue(0);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        LBpersen.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        LBpersen.setText("0 %");

        jLabel15.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("( *wajib dipilih )");

        javax.swing.GroupLayout panelDetail1Layout = new javax.swing.GroupLayout(panelDetail1);
        panelDetail1.setLayout(panelDetail1Layout);
        panelDetail1Layout.setHorizontalGroup(
            panelDetail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetail1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelDetail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelDetail1Layout.createSequentialGroup()
                        .addComponent(RBreguler, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RBexpress))
                    .addComponent(jLabel10)
                    .addGroup(panelDetail1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15))
                    .addComponent(TFtotalharga, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDetail1Layout.createSequentialGroup()
                        .addGroup(panelDetail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LBpersen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panelDetail1Layout.setVerticalGroup(
            panelDetail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetail1Layout.createSequentialGroup()
                .addGroup(panelDetail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDetail1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel8)
                        .addGap(10, 10, 10)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDetail1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(LBpersen, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDetail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDetail1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBreguler)
                    .addComponent(RBexpress))
                .addGap(17, 17, 17)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFtotalharga, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        panelBody.add(panelDetail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 11, -1, 280));

        btnProses.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnProses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tugas_4/upcoming-work.png"))); // NOI18N
        btnProses.setText("PROSES");
        btnProses.setFocusPainted(false);
        btnProses.setOpaque(false);
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });
        panelBody.add(btnProses, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 114, 43));

        btnUlangi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUlangi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tugas_4/refresh.png"))); // NOI18N
        btnUlangi.setText("ULANGI");
        btnUlangi.setFocusPainted(false);
        btnUlangi.setOpaque(false);
        btnUlangi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnUlangiMousePressed(evt);
            }
        });
        panelBody.add(btnUlangi, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 310, 114, 43));

        btnExit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tugas_4/sign-out.png"))); // NOI18N
        btnExit.setText("KELUAR");
        btnExit.setFocusPainted(false);
        btnExit.setOpaque(false);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        panelBody.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 310, 114, 43));

        jPanel1.setBackground(new java.awt.Color(1, 87, 167));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("DETAIL PEMBAYARAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TAnota.setEditable(false);
        TAnota.setColumns(20);
        TAnota.setRows(5);
        jScrollPane1.setViewportView(TAnota);

        javax.swing.GroupLayout panelNotaLayout = new javax.swing.GroupLayout(panelNota);
        panelNota.setLayout(panelNotaLayout);
        panelNotaLayout.setHorizontalGroup(
            panelNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelNotaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panelNotaLayout.setVerticalGroup(
            panelNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNotaLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelBody.add(panelNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 250, 280));

        FormLoundry.add(panelBody, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FormLoundry, javax.swing.GroupLayout.DEFAULT_SIZE, 984, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FormLoundry, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
        int diskon = jSlider1.getValue();
        LBpersen.setText(String.valueOf(diskon)+" %");
    }//GEN-LAST:event_jSlider1StateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        TFnama.setText("");
        TFtelepon.setText("");
        TFberat.setText("");
        TFtotalharga.setText("");
    }//GEN-LAST:event_formWindowOpened

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        // TODO add your handling code here:
        String nama,telepon,paket;
        float total_harga,total_diskon,berat,reguler=11500;
        float diskon = jSlider1.getValue();
        berat = Float.parseFloat(TFberat.getText());
        nama = TFnama.getText();
        telepon = TFtelepon.getText();
        
        if(RBreguler.isSelected()){
           paket = RBreguler.getText();
           total_diskon = (reguler * berat) *(diskon/100);
           total_harga = (reguler*berat) - total_diskon;
        }
        else if(RBexpress.isSelected()){
            paket = RBexpress.getText();
           total_diskon = (float) ((reguler*1.5 * berat) *(diskon/100));
           total_harga = (float) ((reguler*1.5 * berat) - total_diskon);
        }
        else{
            JOptionPane.showMessageDialog(null, "Pilih paket pencucian dulu !!!",
            "Peringatan",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
            TFtotalharga.setText("Rp. "+String.valueOf(total_harga));
            
            TAnota.setText("================================"+
                            "\nNama\t: "+nama+
                            "\nNo Telepon\t: "+telepon+
                            "\nBerat\t: "+berat+" Kg"+
                            "\nPaket\t: "+paket+
                            "\nDiskon\t: Rp "+total_diskon+
                            "\nTotal Bayar\t: Rp "+total_harga+
                            "\n=============================="+
                            "\n"+
                            "\n---------------- TERIMA KASIH ----------------");
    }//GEN-LAST:event_btnProsesActionPerformed

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void TFnamaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TFnamaCaretUpdate
        // TODO add your handling code here:
        if(TFnama.getText().length()==0 || TFberat.getText().equals("0")){
            btnProses.setEnabled(false);
        }else if(TFnama.getText().length()!=0 && TFtelepon.getText().length()!=0 
                && TFberat.getText().length()!=0){
            btnProses.setEnabled(true);
        }
    }//GEN-LAST:event_TFnamaCaretUpdate

    private void TFteleponCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TFteleponCaretUpdate
        // TODO add your handling code here:
        if(TFtelepon.getText().length()==0 || TFberat.getText().equals("0")){
            btnProses.setEnabled(false);
        }
        else if(TFnama.getText().length()!=0 && TFtelepon.getText().length()!=0 
                && TFberat.getText().length()!=0){
            btnProses.setEnabled(true);
        }
    }//GEN-LAST:event_TFteleponCaretUpdate

    private void TFberatCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TFberatCaretUpdate
        // TODO add your handling code here:
        if(TFberat.getText().length()==0 || TFberat.getText().equals("0")){
            btnProses.setEnabled(false);
        }else if(TFnama.getText().length()!=0 && TFtelepon.getText().length()!=0 
                && TFberat.getText().length()!=0){
            btnProses.setEnabled(true);
        }
    }//GEN-LAST:event_TFberatCaretUpdate

    private void btnUlangiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUlangiMousePressed
        // TODO add your handling code here:
        TFnama.setText("");
        TFtelepon.setText("");
        TFberat.setText("");
        jSlider1.setValue(0);
        btnGroupPaket.clearSelection();
        TFtotalharga.setText("");
        TAnota.setText("");
    }//GEN-LAST:event_btnUlangiMousePressed

    private void TFteleponKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFteleponKeyPressed
        // TODO add your handling code here:
        TFtelepon.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent e){
                char karakter = e.getKeyChar();
                if (!((karakter >='0') && (karakter <='9') || (karakter == '\b'))){
                    e.consume();            
                }
            }
        });
    }//GEN-LAST:event_TFteleponKeyPressed

    private void TFberatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFberatKeyPressed
        // TODO add your handling code here:
        TFberat.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent e){
                char karakter = e.getKeyChar();
                if ((((karakter < '0') || (karakter > '9')) && (karakter != '\b')) && (karakter != '.')){
                    e.consume();              
                }
            }
        });
    }//GEN-LAST:event_TFberatKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPelangganLoundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPelangganLoundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPelangganLoundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPelangganLoundry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPelangganLoundry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FormLoundry;
    private javax.swing.JLabel LBpersen;
    private javax.swing.JRadioButton RBexpress;
    private javax.swing.JRadioButton RBreguler;
    private javax.swing.JTextArea TAnota;
    private javax.swing.JTextField TFberat;
    private javax.swing.JTextField TFnama;
    private javax.swing.JTextField TFtelepon;
    private javax.swing.JTextField TFtotalharga;
    private javax.swing.JButton btnExit;
    private javax.swing.ButtonGroup btnGroupPaket;
    private javax.swing.JButton btnProses;
    private javax.swing.JButton btnUlangi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JPanel panelBody;
    private javax.swing.JPanel panelDetail;
    private javax.swing.JPanel panelDetail1;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelNota;
    // End of variables declaration//GEN-END:variables
}
