/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tugas_6;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Miechel
 */
public class FormRumahSakit extends javax.swing.JFrame {

    /**
     * Creates new form FormRumahSakit
     */
    public FormRumahSakit() {
        initComponents();
    }
    
     private DefaultTableModel model;
        private final Connection con = koneksi.getConnection();
        private Statement stt;
        private ResultSet rss;
        private PreparedStatement pst;

    private void InitTable(){
        model = new DefaultTableModel();
//        model.addColumn("ID");
        model.addColumn("Nama Pasien");
        model.addColumn("Tanggal Lahir");
        model.addColumn("Usia");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Diagnosa");
        model.addColumn("Dokter");
        model.addColumn("Ruangan");
        model.addColumn("Tanggal Masuk");
        
        jTable1.setModel(model);
    }
    
    private void TampilData(){
        try{
            String sql = "SELECT * FROM rumahsakit";
            stt = con.createStatement();
            rss = stt.executeQuery(sql);
            while(rss.next()){
                Object[] o = new Object[9];
//                o[0] = rss.getInt("id");
                o[0] = rss.getString("nama_pasien");
                o[1] = rss.getDate("tl");
                o[2] = rss.getInt("usia");
                o[3] = rss.getString("jk");
                o[4] = rss.getString("diagnosa");
                o[5] = rss.getString("dokter");
                o[6] = rss.getString("ruangan");
                o[7] = rss.getDate("tgl_masuk");
                model.addRow(o);
            }
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }
    
     public void TambahData(String nama_pasien, String tl, String usia, String jk,String diagnosa, String dokter,
             String ruangan, String tgl_masuk){
        try{
            String sql = "INSERT INTO rumahsakit VALUES (NULL,'"+nama_pasien+"','"+tl+"','"+usia+"','"+jk+"','"+diagnosa+"','"+dokter+"','"+ruangan+"','"+tgl_masuk+"')";
            stt = con.createStatement();
            stt.executeUpdate(sql);
            model.addRow(new Object[]{nama_pasien,tl,usia,jk,diagnosa,dokter,ruangan,tgl_masuk});
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PanelHeader = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        PanelBody = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        TFnama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        RBperempuan = new javax.swing.JRadioButton();
        TFusia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TFtl = new javax.swing.JTextField();
        RBlaki = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        TFtglmasuk = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CMBdokter = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CMBruangan = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TFdiagnosa = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        LISTdiagnosa = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        BTNtambah = new javax.swing.JButton();
        BTNsimpan = new javax.swing.JButton();
        BTNulangi = new javax.swing.JButton();
        BTNkeluar = new javax.swing.JButton();
        TFcari = new javax.swing.JTextField();
        CMBcari = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("FORM RUMAH SAKIT");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        PanelHeader.setBackground(new java.awt.Color(162, 0, 14));

        jPanel5.setOpaque(false);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Form Pendaftaran Pasien");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("RUMAH SAKIT FKTI SAMARINDA");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Jalan Barong Tongkok No. 1 Kampus Gunung Kelua, Kota Samarinda, Kalimantan Timur");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tugas_6/Home.png"))); // NOI18N
        jLabel19.setMaximumSize(new java.awt.Dimension(70, 70));
        jLabel19.setMinimumSize(new java.awt.Dimension(70, 70));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout PanelHeaderLayout = new javax.swing.GroupLayout(PanelHeader);
        PanelHeader.setLayout(PanelHeaderLayout);
        PanelHeaderLayout.setHorizontalGroup(
            PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(737, Short.MAX_VALUE))
        );
        PanelHeaderLayout.setVerticalGroup(
            PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(PanelHeader, java.awt.BorderLayout.PAGE_START);

        PanelBody.setBackground(new java.awt.Color(255, 186, 192));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama Pasien", "Tanggal Lahir", "Usia", "Jenis Kelamin", "Diagnosa", "Dokter", "Ruangan", "Tanggal Masuk"
            }
        ));
        jTable1.setCellSelectionEnabled(true);
        jScrollPane2.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Pasien", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel3.setOpaque(false);

        TFnama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TFnama.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TFnamaCaretUpdate(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Jenis Kelamin");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Usia");

        buttonGroup1.add(RBperempuan);
        RBperempuan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RBperempuan.setText("P");
        RBperempuan.setOpaque(false);

        TFusia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TFusia.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TFusiaCaretUpdate(evt);
            }
        });
        TFusia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFusiaKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tahun");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nama Pasien");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("(* Format yyyy-mm-dd )");

        TFtl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TFtl.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TFtlCaretUpdate(evt);
            }
        });
        TFtl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFtlKeyPressed(evt);
            }
        });

        buttonGroup1.add(RBlaki);
        RBlaki.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RBlaki.setText("L");
        RBlaki.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tanggal Lahir");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("*) Format Angka");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(RBlaki)
                            .addGap(18, 18, 18)
                            .addComponent(RBperempuan))
                        .addComponent(jLabel4)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(TFtl)
                        .addComponent(jLabel1)
                        .addComponent(TFnama, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(TFusia, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFnama, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFtl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFusia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBlaki)
                    .addComponent(RBperempuan))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Kunjungan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel4.setOpaque(false);

        TFtglmasuk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TFtglmasuk.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TFtglmasukCaretUpdate(evt);
            }
        });
        TFtglmasuk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFtglmasukKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Tanggal Masuk");

        CMBdokter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CMBdokter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "dr. Rita Anitasari Sp.PD", "dr. Rangga Aditya Sp.Anak", "dr. Ferry Miechel Lubis", "dr. Anggitasari Sp.Orp", "dr. Rini Anisa Sari" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("(* Format yyyy-mm-dd )");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Dokter");

        CMBruangan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CMBruangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ruang VVIP", "Ruang VIP", "Ruang Kelas 1 (Anggrek)", "Ruang Kelas 2 (Melati)", "Ruang Kelas 3 (Bersama)" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Ruangan");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TFtglmasuk)
                    .addComponent(CMBruangan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CMBdokter, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CMBdokter, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CMBruangan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFtglmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hasil Diagnosa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel6.setOpaque(false);

        TFdiagnosa.setEditable(false);
        TFdiagnosa.setColumns(20);
        TFdiagnosa.setLineWrap(true);
        TFdiagnosa.setRows(5);
        TFdiagnosa.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TFdiagnosaCaretUpdate(evt);
            }
        });
        jScrollPane1.setViewportView(TFdiagnosa);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pilih Diagnosa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel7.setOpaque(false);

        LISTdiagnosa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LISTdiagnosa.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Diabtes Miletus", "Tubercolousis", "Batuk Berdahak", "Demam Berdarah", "Malaria", "Magh Akut", "Tipus", "Beri-Beri", "Jantung Koroner", "Masuk Angin", "Kencing Manis", "Gejala Tipus", "Iritasi Kulit" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        LISTdiagnosa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LISTdiagnosaMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(LISTdiagnosa);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));

        BTNtambah.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTNtambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tugas_6/user-group-new.png"))); // NOI18N
        BTNtambah.setText("TAMBAH");
        BTNtambah.setFocusPainted(false);
        BTNtambah.setOpaque(false);
        BTNtambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNtambahActionPerformed(evt);
            }
        });

        BTNsimpan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTNsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tugas_6/checklist_pencil-o.png"))); // NOI18N
        BTNsimpan.setText("SIMPAN");
        BTNsimpan.setFocusPainted(false);
        BTNsimpan.setOpaque(false);
        BTNsimpan.setPreferredSize(new java.awt.Dimension(0, 56));
        BTNsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNsimpanActionPerformed(evt);
            }
        });

        BTNulangi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTNulangi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tugas_6/edit-notes.png"))); // NOI18N
        BTNulangi.setText("ULANGI");
        BTNulangi.setFocusPainted(false);
        BTNulangi.setOpaque(false);
        BTNulangi.setPreferredSize(new java.awt.Dimension(0, 56));
        BTNulangi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNulangiActionPerformed(evt);
            }
        });

        BTNkeluar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTNkeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tugas_6/sign-out.png"))); // NOI18N
        BTNkeluar.setText("KELUAR");
        BTNkeluar.setFocusPainted(false);
        BTNkeluar.setOpaque(false);
        BTNkeluar.setPreferredSize(new java.awt.Dimension(0, 56));
        BTNkeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BTNkeluarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNtambah, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(BTNsimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNulangi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNkeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTNtambah, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNulangi, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TFcari.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TFcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFcariKeyTyped(evt);
            }
        });

        CMBcari.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CMBcari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nama_Pasien", "Dokter" }));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tugas_6/zoom.png"))); // NOI18N
        jLabel12.setText("Cari Data");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("By");

        javax.swing.GroupLayout PanelBodyLayout = new javax.swing.GroupLayout(PanelBody);
        PanelBody.setLayout(PanelBodyLayout);
        PanelBodyLayout.setHorizontalGroup(
            PanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(PanelBodyLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(TFcari, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CMBcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelBodyLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PanelBodyLayout.setVerticalGroup(
            PanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFcari, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CMBcari, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(PanelBody, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        BTNsimpan.setEnabled(false);
        BTNulangi.setEnabled(false);
        TFdiagnosa.setEnabled(false);
        TFnama.setEnabled(false);
        TFtl.setEnabled(false);
        CMBdokter.setEnabled(false);
        TFusia.setEnabled(false);
        RBlaki.setEnabled(false);
        RBperempuan.setEnabled(false);
        TFtglmasuk.setEnabled(false);
        CMBdokter.setEnabled(false);
        CMBruangan.setEnabled(false);
        LISTdiagnosa.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void BTNtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNtambahActionPerformed
        // TODO add your handling code here:
//        BTNsimpan.setEnabled(false);
        BTNulangi.setEnabled(true);
        TFnama.setEnabled(true);
        TFtl.setEnabled(true);
        TFdiagnosa.setEnabled(true);
        CMBdokter.setEnabled(true);
        TFusia.setEnabled(true);
        RBlaki.setEnabled(true);
        RBperempuan.setEnabled(true);
        TFtglmasuk.setEnabled(true);
        CMBdokter.setEnabled(true);
        CMBruangan.setEnabled(true);
        LISTdiagnosa.setEnabled(true);
    }//GEN-LAST:event_BTNtambahActionPerformed

    private void BTNkeluarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNkeluarMousePressed
        // TODO add your handling code here:
        int pilih = JOptionPane.showConfirmDialog(this, "Ingin Keluar Dari Aplikasi ?","Confirm Keluar",JOptionPane.YES_OPTION);
        if(pilih==JOptionPane.YES_OPTION){
        System.exit(0);
        }
    }//GEN-LAST:event_BTNkeluarMousePressed

    private void TFnamaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TFnamaCaretUpdate
        // TODO add your handling code here:
        if (TFnama.getText().length()== 0 ||  TFtl.getText().length()== 0 ||
            TFusia.getText().length()== 0 ||  TFtglmasuk.getText().length()==0 ||
            TFdiagnosa.getText().length()== 0){
            BTNsimpan.setEnabled(false);
        }
        else{
            BTNsimpan.setEnabled(true);
        }
    }//GEN-LAST:event_TFnamaCaretUpdate

    private void TFtlCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TFtlCaretUpdate
        // TODO add your handling code here:
        if (TFnama.getText().length()== 0 ||  TFtl.getText().length()== 0 ||
            TFusia.getText().length()== 0 ||  TFtglmasuk.getText().length()==0 ||
            TFdiagnosa.getText().length()== 0){
            BTNsimpan.setEnabled(false);
        }
        else{
            BTNsimpan.setEnabled(true);
        }
    }//GEN-LAST:event_TFtlCaretUpdate

    private void TFusiaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TFusiaCaretUpdate
        // TODO add your handling code here:
        if (TFnama.getText().length()== 0 ||  TFtl.getText().length()== 0 ||
            TFusia.getText().length()== 0 ||  TFtglmasuk.getText().length()==0 ||
            TFdiagnosa.getText().length()== 0){
            BTNsimpan.setEnabled(false);
        }
        else{
            BTNsimpan.setEnabled(true);
        }
    }//GEN-LAST:event_TFusiaCaretUpdate

    private void TFtglmasukCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TFtglmasukCaretUpdate
        // TODO add your handling code here:
        if (TFnama.getText().length()== 0 ||  TFtl.getText().length()== 0 ||
            TFusia.getText().length()== 0 ||  TFtglmasuk.getText().length()==0 ||
            TFdiagnosa.getText().length()== 0){
            BTNsimpan.setEnabled(false);
        }
        else{
            BTNsimpan.setEnabled(true);
        }
    }//GEN-LAST:event_TFtglmasukCaretUpdate

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        InitTable();
        TampilData();
    }//GEN-LAST:event_formComponentShown

    private void BTNsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNsimpanActionPerformed
        // TODO add your handling code here:
        int pilih = JOptionPane.showConfirmDialog(this, "Yakin ingin simpan data ?","Confirm Simpan",JOptionPane.YES_OPTION);
        if(pilih==JOptionPane.YES_OPTION){
        String jk;
        String nama_pasien = TFnama.getText();
        String tl = TFtl.getText();
        String usia = TFusia.getText();
        
        if(RBlaki.isSelected()){
           jk = RBlaki.getText();
        }
        else if(RBperempuan.isSelected()){
            jk = RBperempuan.getText();
        }
        else{
            JOptionPane.showMessageDialog(null, "Pilih jenis kelamin dulu !!!",
            "Peringatan",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        
        String diagnosa = TFdiagnosa.getText();
        String dokter = CMBdokter.getSelectedItem().toString();
        String ruangan = CMBruangan.getSelectedItem().toString();
        String tgl_masuk = TFtglmasuk.getText();
        TambahData(nama_pasien,tl,usia,jk,diagnosa,dokter,ruangan,tgl_masuk);
        bersih();
        }
    }//GEN-LAST:event_BTNsimpanActionPerformed
     public void bersih(){
        TFnama.setText("");
        TFtl.setText("");
        CMBdokter.setSelectedItem("dr. Rita Anitasari Sp.PD");
        TFusia.setText("");
        buttonGroup1.clearSelection();
        TFtglmasuk.setText("");
        TFdiagnosa.setText("");
        CMBruangan.setSelectedItem("Ruang VVIP");
        LISTdiagnosa.clearSelection();
        TFnama.requestFocus();
     }
    private void BTNulangiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNulangiActionPerformed
        // TODO add your handling code here:
        TFnama.setText("");
        TFtl.setText("");
        CMBdokter.setSelectedItem("dr. Rita Anitasari Sp.PD");
        TFusia.setText("");
        buttonGroup1.clearSelection();
        TFtglmasuk.setText("");
        TFdiagnosa.setText("");
        CMBruangan.setSelectedItem("Ruang VVIP");
        LISTdiagnosa.clearSelection();
        TFnama.requestFocus();
    }//GEN-LAST:event_BTNulangiActionPerformed

    private void TFcariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFcariKeyTyped
        // TODO add your handling code here:
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        String berdasarkan = CMBcari.getSelectedItem().toString();
        try {
            
            String sql="SELECT * FROM rumahsakit where "+berdasarkan+" like '%"+TFcari.getText()+"%'";
            stt = con. createStatement();
            rss = stt. executeQuery(sql);
            ResultSet rss=stt.executeQuery(sql);
            while (rss.next()) {
                Object[] o=new Object[9];
                o[0] = rss.getString("nama_pasien");
                o[1] = rss.getDate("tl");
                o[2] = rss.getInt("usia");
                o[3] = rss.getString("jk");
                o[4] = rss.getString("diagnosa");
                o[5] = rss.getString("dokter");
                o[6] = rss.getString("ruangan");
                o[7] = rss.getString("tgl_masuk");
                model.addRow(o);
            }
            stt.close();
            rss.close();
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan");
        }                            
    }//GEN-LAST:event_TFcariKeyTyped

    private void TFusiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFusiaKeyPressed
        // TODO add your handling code here:
        TFusia.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent e){
                char karakter = e.getKeyChar();
                if (!((karakter >='0') && (karakter <='9') || (karakter == '\b'))){
                    e.consume();            
                }
            }
        });
    }//GEN-LAST:event_TFusiaKeyPressed

    private void TFtlKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFtlKeyPressed
        // TODO add your handling code here:
        TFtl.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent e){
                char karakter = e.getKeyChar();
                if ((((karakter < '0') || (karakter > '9')) && (karakter != '\b')) && (karakter != '-')){
                    e.consume();              
                }
            }
        });
    }//GEN-LAST:event_TFtlKeyPressed

    private void TFtglmasukKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFtglmasukKeyPressed
        // TODO add your handling code here:
         TFtglmasuk.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent e){
                char karakter = e.getKeyChar();
                if ((((karakter < '0') || (karakter > '9')) && (karakter != '\b')) && (karakter != '-')){
                    e.consume();              
                }
            }
        });
    }//GEN-LAST:event_TFtglmasukKeyPressed

    private void LISTdiagnosaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LISTdiagnosaMousePressed
        // TODO add your handling code here:
        TFdiagnosa.setText(LISTdiagnosa.getSelectedValuesList().toString());
    }//GEN-LAST:event_LISTdiagnosaMousePressed

    private void TFdiagnosaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TFdiagnosaCaretUpdate
        // TODO add your handling code here:
        if (TFnama.getText().length()== 0 ||  TFtl.getText().length()== 0 ||
            TFusia.getText().length()== 0 ||  TFtglmasuk.getText().length()==0 ||
            TFdiagnosa.getText().length()== 0){
            BTNsimpan.setEnabled(false);
        }
        else{
            BTNsimpan.setEnabled(true);
        }
    }//GEN-LAST:event_TFdiagnosaCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRumahSakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRumahSakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRumahSakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRumahSakit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRumahSakit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNkeluar;
    private javax.swing.JButton BTNsimpan;
    private javax.swing.JButton BTNtambah;
    private javax.swing.JButton BTNulangi;
    private javax.swing.JComboBox<String> CMBcari;
    private javax.swing.JComboBox<String> CMBdokter;
    private javax.swing.JComboBox<String> CMBruangan;
    private javax.swing.JList<String> LISTdiagnosa;
    private javax.swing.JPanel PanelBody;
    private javax.swing.JPanel PanelHeader;
    private javax.swing.JRadioButton RBlaki;
    private javax.swing.JRadioButton RBperempuan;
    private javax.swing.JTextField TFcari;
    private javax.swing.JTextArea TFdiagnosa;
    private javax.swing.JTextField TFnama;
    private javax.swing.JTextField TFtglmasuk;
    private javax.swing.JTextField TFtl;
    private javax.swing.JTextField TFusia;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
